# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib mixeff, .registration = TRUE
NULL

#' Parse an lme4-style formula string and return its canonical form.
#'
#' On success, returns the formula's `Display` rendering as a single
#' character string. On parse failure, throws an extendr error whose message
#' is prefixed with `mm_formula_error:` so the R wrapper can convert it to a
#' typed `mm_formula_error` condition.
#'
#' @noRd
mm_parse_formula <- function(formula) .Call(wrap__mm_parse_formula, formula)

#' Return the package's formula manifest.
#'
#' A small, versioned record of what the wrapper supports today. R callers
#' use this to gate behavior on capabilities rather than hard-coding
#' assumptions, and to record provenance on `mm_fit` artifacts.
#'
#' @noRd
mm_formula_manifest <- function() .Call(wrap__mm_formula_manifest)

#' Negotiate a single schema declaration against the wrapper's known set.
#'
#' Returns `TRUE` on a clean match. On mismatch or unknown schema, throws
#' an extendr error prefixed with `mm_schema_error:` for routing to the
#' typed condition on the R side. The full negotiation logic (multi-schema
#' headers, version-range comparisons) lives in R; this function is a
#' pin-point primitive over the closed `KNOWN_SCHEMAS` table.
#'
#' @noRd
mm_json_negotiate_one <- function(name, version) .Call(wrap__mm_json_negotiate_one, name, version)

#' Return the closed list of (schema_name, schema_version) the wrapper
#' currently knows how to consume.
#'
#' @noRd
mm_json_known_schemas <- function() .Call(wrap__mm_json_known_schemas)

#' Compile a formula against a data manifest and return the artifact JSON.
#'
#' Runs the upstream `parse_formula` -> `compile_formula_ir` ->
#' `CompiledModelArtifact::new` -> `attach_design_audit` pipeline and
#' returns the serialized `CompiledModelArtifact` (schema
#' `mixedmodels.compiled_model_artifact` v1). No fit happens here — that
#' lands in Phase 1.E.
#'
#' Inputs follow the wire format described in `data.rs`. The R wrapper
#' (`compile_model()`) is the only supported caller; it validates the
#' shape before invoking this primitive, so most error paths surface as
#' `mm_data_error:` / `mm_formula_error:` / `mm_schema_error:` tagged
#' strings the R side routes to typed conditions.
#'
#' @noRd
mm_compile_model_json <- function(formula, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered) .Call(wrap__mm_compile_model_json, formula, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered)

#' Fit a linear mixed-effects model and return the fit payload JSON.
#'
#' This is the Phase 1.E fit primitive: parse formula, build the upstream
#' `DataFrame`, construct `LinearMixedModel`, run `.fit(reml)`, then return
#' the post-fit `CompiledModelArtifact` plus flat extractor-friendly numeric
#' duplicates. R owns the user-facing S3 surface; Rust owns the numerical fit
#' and the compiler/audit artifact.
#'
#' @noRd
mm_fit_lmm_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json) .Call(wrap__mm_fit_lmm_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json)

#' Fit a generalized linear mixed-effects model and return the fit payload JSON.
#'
#' This is the Stage B.1 GLMM fit primitive. The R layer owns formula/data
#' validation and user-facing S3 shape; Rust owns construction of the upstream
#' `GeneralizedLinearMixedModel`, the PIRLS fit, and the compiler artifact.
#' `method = "pirls_profiled"` maps to upstream `fast = true`. `method =
#' "joint_laplace"` maps to the labelled upstream `fast = false, n_agq = 1`
#' joint route.
#'
#' @noRd
mm_fit_glmm_json <- function(formula, family, link, method, n_agq, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, offset, control_json) .Call(wrap__mm_fit_glmm_json, formula, family, link, method, n_agq, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, offset, control_json)

#' Evaluate fixed-effect contrast rows through the Rust inference contract.
#'
#' @noRd
mm_fixed_effect_contrast_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, l_values, nrow, ncol, labels, rhs, method) .Call(wrap__mm_fixed_effect_contrast_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, l_values, nrow, ncol, labels, rhs, method)

#' Evaluate fixed-effect-null bootstrap contrast rows through Rust.
#'
#' @noRd
mm_fixed_effect_bootstrap_contrast_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, l_values, nrow, ncol, labels, rhs, bootstrap_options_json) .Call(wrap__mm_fixed_effect_bootstrap_contrast_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, l_values, nrow, ncol, labels, rhs, bootstrap_options_json)

#' Evaluate a full-model bootstrap contrast payload for fixed-effect
#' confidence intervals. This target simulates from the fitted model and
#' returns interval summaries plus replicate accounting; it does not certify
#' fixed-effect hypothesis-test p-values.
#'
#' @noRd
mm_full_model_bootstrap_contrast_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, l_values, nrow, ncol, labels, rhs, bootstrap_options_json, levels) .Call(wrap__mm_full_model_bootstrap_contrast_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, l_values, nrow, ncol, labels, rhs, bootstrap_options_json, levels)

#' Evaluate a fixed-effect-null bootstrap *term* row (joint Wald/F over an
#' arbitrary L matrix) through Rust. Single-df hypotheses produce a t-form
#' row; multi-df hypotheses produce an F-form row with `numerator_df` set
#' to the effective restriction rank. Wraps
#' `LinearMixedModel::fixed_effect_null_bootstrap_inference_row` with
#' `kind = Term`.
#'
#' @noRd
mm_fixed_effect_bootstrap_term_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, l_values, nrow, ncol, label, rhs, bootstrap_options_json) .Call(wrap__mm_fixed_effect_bootstrap_term_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, l_values, nrow, ncol, label, rhs, bootstrap_options_json)

#' Evaluate fixed-effect term rows through Rust-owned term hypotheses.
#'
#' @noRd
mm_fixed_effect_term_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, method, term_test_type) .Call(wrap__mm_fixed_effect_term_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, method, term_test_type)

#' Run a parametric bootstrap likelihood-ratio test between two LMMs fitted
#' to the same data. Both models must be ML (the upstream engine refuses
#' REML). Returns a serialised `BootstrapLikelihoodRatioTest`.
#'
#' @noRd
mm_bootstrap_lrt_json <- function(reduced_formula, alternative_formula, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, bootstrap_options_json) .Call(wrap__mm_bootstrap_lrt_json, reduced_formula, alternative_formula, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, bootstrap_options_json)

#' Build an upstream model-comparison table for fitted LMM payloads.
#'
#' Each list element is the R-side bridge payload for one fitted model
#' (`formula_string`, `REML`, `spec_data`, `weights`, and `control_json`).
#' Returning the upstream `ModelComparisonTable` keeps nestedness, ML-refit,
#' information-criteria, and reason-code rules owned by the Rust contract.
#'
#' @noRd
mm_compare_models_json <- function(model_payloads, method, refit_policy) .Call(wrap__mm_compare_models_json, model_payloads, method, refit_policy)

#' Boundary-aware variance-component likelihood-ratio test.
#'
#' `reduced_payload` may be NULL when the tested random term is the only
#' random-effect term. In that case the reduced model is the fixed-effect
#' linear model built from the full model's response and fixed-effect design.
#' Otherwise it is the bridge payload for the reduced LMM.
#'
#' @noRd
mm_boundary_lrt_json <- function(reduced_payload, full_payload, reduced_formula) .Call(wrap__mm_boundary_lrt_json, reduced_payload, full_payload, reduced_formula)

#' Bounded convergence verification for a fitted LMM.
#'
#' Rebuilds and refits the model from the R-side bridge payload (the same
#' payload `mm_compare_models_json` / `mm_boundary_lrt_json` use), then runs
#' the engine's verification workflow: restart from the optimum, jittered
#' restarts, and (optionally) an alternate-optimizer consensus pass. The
#' verifier re-runs its own fits internally, so no optimizer state has to
#' cross the boundary. `options_json` carries R-side overrides; absent
#' fields keep the engine defaults.
#'
#' @noRd
mm_verify_convergence_json <- function(fit_payload, options_json) .Call(wrap__mm_verify_convergence_json, fit_payload, options_json)

#' Render an `audit_design()` artifact as text.
#'
#' Takes the JSON produced by `mm_compile_model_json` and returns the
#' upstream `ModelAuditReport::Display` rendering — the source of truth
#' for audit wording. R's `print.mm_audit()` calls this and emits the
#' result with `cat()`. Routing all English wording through this entry
#' point keeps the R9 "no advice creep" contract enforceable: reviewers
#' see drift in one place (the Rust crate), not scattered across R
#' formatters.
#'
#' @noRd
mm_audit_report_text <- function(artifact_json) .Call(wrap__mm_audit_report_text, artifact_json)

#' Render the compact `audit_design()` summary as text.
#'
#' The compact counterpart to `mm_audit_report_text`: it returns the
#' upstream `ModelAuditReport::render_summary` rendering (Audit Summary
#' plus the Requested Model section). R's default `print.mm_audit()`
#' emits this, so the compact view stays fully upstream-authored — the
#' R9 "no advice creep" contract holds without R slicing rendered text.
#'
#' @noRd
mm_audit_report_summary_text <- function(artifact_json) .Call(wrap__mm_audit_report_summary_text, artifact_json)

#' Serialize the structured `ModelAuditReport` for an `audit_design()` artifact.
#'
#' This is the structured counterpart to `mm_audit_report_text`: Rust still
#' authors the report and random-term-card wording, while R receives the
#' already-authored fields for later formatters such as `explain_model()`.
#'
#' @noRd
mm_audit_report_json <- function(artifact_json) .Call(wrap__mm_audit_report_json, artifact_json)

#' Conditional variance matrices of the random effects, serialized for R.
#'
#' Mirrors `lme4::condVar` / `ranef(condVar = TRUE)`. Each RE term yields a
#' `p × p × n` PSD array (one `p × p` block per grouping level), flattened
#' column-major so `array(payload$postvar, dim = payload$dim)` reconstructs the
#' 3-D array R expects. `names` indexes the leading two dimensions (slope
#' names per term) and `levels` indexes the trailing dimension.
#'
#' @noRd
mm_lmm_cond_var_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json) .Call(wrap__mm_lmm_cond_var_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json)

#' New-data predictions through `LinearMixedModel::predict_new`.
#'
#' `allow_new_levels_policy` is the string-form of `NewReLevels`:
#'   "error"       -> NewReLevels::Error
#'   "population"  -> NewReLevels::Population
#'   "missing"     -> NewReLevels::Missing
#'
#' Returns a JSON payload carrying one prediction per `newdata` row.
#' Predictions whose upstream value is `None` (unseen grouping level under
#' the "missing" policy) are encoded as JSON `null`, which the R side
#' translates to `NA_real_`.
#'
#' @noRd
mm_lmm_predict_new_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, new_column_order, new_numeric_columns, new_categorical_values, new_categorical_levels, new_categorical_ordered, allow_new_levels_policy) .Call(wrap__mm_lmm_predict_new_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, new_column_order, new_numeric_columns, new_categorical_values, new_categorical_levels, new_categorical_ordered, allow_new_levels_policy)

#' New-data prediction VARIANCE / intervals through
#' `LinearMixedModel::predict_new_variance_with_level`.
#'
#' Returns the engine `PredictionVariancePayload` JSON (serde): one row per
#' `newdata` row carrying `se_fit`, the fixed / random / covariance variance
#' components, `confidence_*` / `prediction_*` bounds at `level`, and a
#' row-level `status` / `reason` (unavailable for new grouping levels). The R
#' side maps unavailable rows to `NA` with the reason, preserving the
#' no-fake-certainty contract.
#'
#' `allow_new_levels_policy` is the string form of `NewReLevels`
#' ("error" | "population" | "missing").
#'
#' @noRd
mm_lmm_predict_new_variance_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, new_column_order, new_numeric_columns, new_categorical_values, new_categorical_levels, new_categorical_ordered, allow_new_levels_policy, level) .Call(wrap__mm_lmm_predict_new_variance_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, new_column_order, new_numeric_columns, new_categorical_values, new_categorical_levels, new_categorical_ordered, allow_new_levels_policy, level)

#' New-data prediction VARIANCE / intervals for a GLMM through
#' `GeneralizedLinearMixedModel::predict_new_variance_with_level`.
#'
#' `scale` is the string form of `GlmmPredictionScale` ("link" | "response");
#' `allow_new_levels_policy` is the string form of `NewReLevels`. Returns the
#' engine `PredictionVariancePayload` JSON. Certified (joint-Laplace) fits
#' return available conditional rows; fast-PIRLS / new-level rows are marked
#' degraded / unavailable with a row-level reason.
#'
#' @noRd
mm_glmm_predict_new_variance_json <- function(formula, family, link, method, n_agq, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, offset, control_json, new_column_order, new_numeric_columns, new_categorical_values, new_categorical_levels, new_categorical_ordered, scale, allow_new_levels_policy, level) .Call(wrap__mm_glmm_predict_new_variance_json, formula, family, link, method, n_agq, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, offset, control_json, new_column_order, new_numeric_columns, new_categorical_values, new_categorical_levels, new_categorical_ordered, scale, allow_new_levels_policy, level)

#' Profile-likelihood confidence intervals through
#' `mixeff_rs::stats::profile_confint_payload`.
#'
#' `level` is the confidence level in `(0, 1)`. The upstream payload carries
#' both the computed intervals and the raw profile rows. Under REML the
#' upstream contract omits beta from the profiled parameters; the R-side
#' wrapper turns this absence into a typed `profile_beta_unavailable_under_reml`
#' reason rather than fabricating beta CIs.
#'
#' @noRd
mm_lmm_profile_confint_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, level) .Call(wrap__mm_lmm_profile_confint_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, categorical_ordered, weights, control_json, level)

#' Demo of the interrupt bridge — a no-op loop that yields to R between
#' iterations so Ctrl-C can terminate it. Returns `iters` on clean
#' completion.
#'
#' Used in Phase 0 only as a smoke test that the interrupt FFI binding is
#' linked correctly. Phase 1+ replaces this with the hook called from
#' inside fit / inference loops.
#'
#' @noRd
mm_interrupt_demo <- function(iters) .Call(wrap__mm_interrupt_demo, iters)

# nolint end
