# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib mixeff, .registration = TRUE
NULL

#' Parse an lme4-style formula string and return its canonical form.
#'
#' On success, returns the formula's `Display` rendering as a single
#' character string. On parse failure, throws an extendr error whose message
#' is prefixed with `mm_formula_error:` so the R wrapper can convert it to a
#' typed `mm_formula_error` condition.
#'
#' @noRd
mm_parse_formula <- function(formula) .Call(wrap__mm_parse_formula, formula)

#' Return the package's formula manifest.
#'
#' A small, versioned record of what the wrapper supports today. R callers
#' use this to gate behavior on capabilities rather than hard-coding
#' assumptions, and to record provenance on `mm_fit` artifacts.
#'
#' @noRd
mm_formula_manifest <- function() .Call(wrap__mm_formula_manifest)

#' Negotiate a single schema declaration against the wrapper's known set.
#'
#' Returns `TRUE` on a clean match. On mismatch or unknown schema, throws
#' an extendr error prefixed with `mm_schema_error:` for routing to the
#' typed condition on the R side. The full negotiation logic (multi-schema
#' headers, version-range comparisons) lives in R; this function is a
#' pin-point primitive over the closed `KNOWN_SCHEMAS` table.
#'
#' @noRd
mm_json_negotiate_one <- function(name, version) .Call(wrap__mm_json_negotiate_one, name, version)

#' Return the closed list of (schema_name, schema_version) the wrapper
#' currently knows how to consume.
#'
#' @noRd
mm_json_known_schemas <- function() .Call(wrap__mm_json_known_schemas)

#' Compile a formula against a data manifest and return the artifact JSON.
#'
#' Runs the upstream `parse_formula` -> `compile_formula_ir` ->
#' `CompiledModelArtifact::new` -> `attach_design_audit` pipeline and
#' returns the serialized `CompiledModelArtifact` (schema
#' `mixedmodels.compiled_model_artifact` v1). No fit happens here — that
#' lands in Phase 1.E.
#'
#' Inputs follow the wire format described in `data.rs`. The R wrapper
#' (`compile_model()`) is the only supported caller; it validates the
#' shape before invoking this primitive, so most error paths surface as
#' `mm_data_error:` / `mm_formula_error:` / `mm_schema_error:` tagged
#' strings the R side routes to typed conditions.
#'
#' @noRd
mm_compile_model_json <- function(formula, column_order, numeric_columns, categorical_values, categorical_levels) .Call(wrap__mm_compile_model_json, formula, column_order, numeric_columns, categorical_values, categorical_levels)

#' Fit a linear mixed-effects model and return the fit payload JSON.
#'
#' This is the Phase 1.E fit primitive: parse formula, build the upstream
#' `DataFrame`, construct `LinearMixedModel`, run `.fit(reml)`, then return
#' the post-fit `CompiledModelArtifact` plus flat extractor-friendly numeric
#' duplicates. R owns the user-facing S3 surface; Rust owns the numerical fit
#' and the compiler/audit artifact.
#'
#' @noRd
mm_fit_lmm_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json) .Call(wrap__mm_fit_lmm_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json)

#' Evaluate fixed-effect contrast rows through the Rust inference contract.
#'
#' @noRd
mm_fixed_effect_contrast_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, l_values, nrow, ncol, labels, rhs, method) .Call(wrap__mm_fixed_effect_contrast_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, l_values, nrow, ncol, labels, rhs, method)

#' Evaluate fixed-effect-null bootstrap contrast rows through Rust.
#'
#' @noRd
mm_fixed_effect_bootstrap_contrast_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, l_values, nrow, ncol, labels, rhs, bootstrap_options_json) .Call(wrap__mm_fixed_effect_bootstrap_contrast_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, l_values, nrow, ncol, labels, rhs, bootstrap_options_json)

#' Evaluate a full-model bootstrap contrast payload for fixed-effect
#' confidence intervals. This target simulates from the fitted model and
#' returns interval summaries plus replicate accounting; it does not certify
#' fixed-effect hypothesis-test p-values.
#'
#' @noRd
mm_full_model_bootstrap_contrast_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, l_values, nrow, ncol, labels, rhs, bootstrap_options_json, levels) .Call(wrap__mm_full_model_bootstrap_contrast_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, l_values, nrow, ncol, labels, rhs, bootstrap_options_json, levels)

#' Evaluate a fixed-effect-null bootstrap *term* row (joint Wald/F over an
#' arbitrary L matrix) through Rust. Single-df hypotheses produce a t-form
#' row; multi-df hypotheses produce an F-form row with `numerator_df` set
#' to the effective restriction rank. Wraps
#' `LinearMixedModel::fixed_effect_null_bootstrap_inference_row` with
#' `kind = Term`.
#'
#' @noRd
mm_fixed_effect_bootstrap_term_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, l_values, nrow, ncol, label, rhs, bootstrap_options_json) .Call(wrap__mm_fixed_effect_bootstrap_term_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, l_values, nrow, ncol, label, rhs, bootstrap_options_json)

#' Evaluate fixed-effect term rows through Rust-owned term hypotheses.
#'
#' @noRd
mm_fixed_effect_term_json <- function(formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, method) .Call(wrap__mm_fixed_effect_term_json, formula, reml, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, method)

#' Run a parametric bootstrap likelihood-ratio test between two LMMs fitted
#' to the same data. Both models must be ML (the upstream engine refuses
#' REML). Returns a serialised `BootstrapLikelihoodRatioTest`.
#'
#' @noRd
mm_bootstrap_lrt_json <- function(reduced_formula, alternative_formula, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, bootstrap_options_json) .Call(wrap__mm_bootstrap_lrt_json, reduced_formula, alternative_formula, column_order, numeric_columns, categorical_values, categorical_levels, weights, control_json, bootstrap_options_json)

#' Render an `audit_design()` artifact as text.
#'
#' Takes the JSON produced by `mm_compile_model_json` and returns the
#' upstream `ModelAuditReport::Display` rendering — the source of truth
#' for audit wording. R's `print.mm_audit()` calls this and emits the
#' result with `cat()`. Routing all English wording through this entry
#' point keeps the R9 "no advice creep" contract enforceable: reviewers
#' see drift in one place (the Rust crate), not scattered across R
#' formatters.
#'
#' @noRd
mm_audit_report_text <- function(artifact_json) .Call(wrap__mm_audit_report_text, artifact_json)

#' Serialize the structured `ModelAuditReport` for an `audit_design()` artifact.
#'
#' This is the structured counterpart to `mm_audit_report_text`: Rust still
#' authors the report and random-term-card wording, while R receives the
#' already-authored fields for later formatters such as `explain_model()`.
#'
#' @noRd
mm_audit_report_json <- function(artifact_json) .Call(wrap__mm_audit_report_json, artifact_json)

#' Demo of the interrupt bridge — a no-op loop that yields to R between
#' iterations so Ctrl-C can terminate it. Returns `iters` on clean
#' completion.
#'
#' Used in Phase 0 only as a smoke test that the interrupt FFI binding is
#' linked correctly. Phase 1+ replaces this with the hook called from
#' inside fit / inference loops.
#'
#' @noRd
mm_interrupt_demo <- function(iters) .Call(wrap__mm_interrupt_demo, iters)

# nolint end
